spring:
  profiles:
    active: dev
  application:
    name: "My variant"
    version: "0.1"
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/students100
    username: postgres
    password: 1511
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
          ddl-auto: update
server:
  port: 8081

logging:
  level:
    org.springframework.web: DEBUG